### ISSUE TITLE
gp_backend_free()

### ISSUE THREAD

**Issue by RobLoach** [gfxprim/gfxprim#42]
Noticed a bunch of the examples don't clear the memory from the backend. Would be nice if we had a nice helper function for that. Something like....

``` c

void gp_backend_free(gp_backend *self) {
	if (self->pixmap != NULL)
		gp_pixmap_free(self->pixmap);

	if (self->name != NULL)
		free(self->name);
	
	if (self->timers != NULL)
		free(self->timers);

	if (self->clipboard_data != NULL)
		free(self->clipboard_data);
}
```

Do you think it should call ->exit before clearing?

**Comment by metan-ucw** [comment]
Actually the clipboard data should be freed in the ->exit function. The backend exit looks like:

```
void gp_backend_exit(gp_backend *self)
{
        struct gp_clipboard op = {.op = GP_CLIPBOARD_CLEAR};

        if (!self)
                return;

        gp_backend_clipboard(self, &op);

        self->exit(self);
}
```

Note that we send clipboard clear request before we destroy the backend, which, among other things, should free the clipboard data. For x11 backend it also clears the clipboard owner from the X server.

The pixmap should be freed in the backend ->exit function, at least for x11 we do that in the `destroy_ximage()` called from the x11_exit() that frees it if it was allocated. In the case of SHM the pixmap is backed by shm memory and the pixmap cannot be even freed by gp_pixmap_free() since it's mapped as SHM memory.

The backend name is static string that is not allocated at all, no need to free it.

And the timers are supposed to be maintained by the application, that means that there is no additional memory allocated for the timer heap besides the actual timer structures that are supposed to be allocated by the application and freed by the application when they are no longer needed. For example they can be freed in the timer callback.

That should explain how the pointers are maintained, does that explain everything or did I miss something?
